<?php
    $this->headScript()->captureStart()
?>
    var animalRows = <?php echo $animal; ?>;
<?php
    $this->headScript()->captureEnd()
?>
<article>
    <h1>TODO LIST</h1>
    <div class="form-horizontal">
        <div class="form-group">
            <label for="description" class="col-sm-2 control-label">Description</label>
            <div class="col-sm-10">
	            <input type="text" class="form-control" id="description" placeholder="Description" name="description" value="">
            </div>
        </div>
	    <div class="form-group">
		    <label for="url" class="col-sm-2 control-label">URL</label>
		    <div class="col-sm-10">
			    <input type="text" class="form-control" id="url" placeholder="URL" name="url" value="">
		    </div>
	    </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
	            <button id="send-animal" type="submit" class="btn btn-default">Add animal</button>
            </div>
        </div>
        <input type="hidden" value="" name="id">
    </div>

    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>URL</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Description</td>
                <td>URL</td>
                <td><i class="fa fa-pencil-square-o" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Description</td>
                <td>URL 2</td>
                <td><i class="fa fa-pencil-square-o" aria-hidden="true"></i></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Description</td>
                <td>URL 3</td>
                <td><i class="fa fa-pencil-square-o" aria-hidden="true"></i></td>
            </tr>
        </tbody>
    </table>

</article>